#!/usr/bin/env zsh

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

pushd $DOTFILES

STOW_FOLDERS=$(ls -d */ | sed 's#/##' | tr '\n' ',' | sed 's/,$//')

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g"); do
    stow -D $folder
    stow $folder
done

popd

