#!/bin/sh

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
HISTFILE="$XDG_DATA_HOME"/zsh/.zhistory
HISTSIZE=100000
SAVEHIST=100000

# Man pages
export MANPAGER='nvim +Man!'
export MANWIDTH=999

# Editor
export EDITOR='nvim'
export VISUAL=nvim

# PATH
export PATH="$HOME/.local/bin":$PATH

# You-should-use
export YSU_IGNORED_ALIASES=("vim" "vi")
